Move plaquette into main page
betagouv/renforts pull request #44
Opened 2021-01-21 13:22 UTC by lbois

2021-01-21 15:15 UTC, estellecomment commented on views/partials/missions.ejs
> +      peut être réalisée. (Vous pouvez aller voir la section :
```suggestion
      peut être réalisée. (Vous pouvez aller voir dans la Foire Aux Questions :
```

2021-01-21 15:17 UTC, estellecomment requested changes
Cool !
Du coup on a le même contenu à deux endroits du site. Donc je propose de l'enlever de la FAQ.
Je propose de garder le titre de la question de FAQ, mais remplacer le contenu par une suggestion d'aller voir sur la landing page, avec un lien.

2021-01-21 15:17 UTC, estellecomment commented on views/partials/missions.ejs
> +      <a href="#accord-de-ma-hiérarchie">Comment obtenir l'accord de mon supérieur hiérarchique ?</a>)
lien cassé

2021-01-21 15:17 UTC, estellecomment commented on views/partials/missions.ejs
> +        href="#cadre-juridique">section cadre juridique</a>)
lien cassé

2021-01-21 15:17 UTC, estellecomment commented on views/partials/missions.ejs
> +      Les deux services RH négocient une convention. (Voir le modèle de convention proposée : <a
```suggestion
      Les deux services RH négocient une convention. (Voir le modèle de convention proposée dans la Foire Aux Questions : <a
```

2021-01-21 16:51 UTC, lbois commented on views/partials/missions.ejs
> +      <a href="#accord-de-ma-hiérarchie">Comment obtenir l'accord de mon supérieur hiérarchique ?</a>)
Je l'ai deja supprimé de la FAQ

2021-01-21 16:56 UTC, lbois commented on views/partials/missions.ejs
> +      <a href="#accord-de-ma-hiérarchie">Comment obtenir l'accord de mon supérieur hiérarchique ?</a>)
J'ai resolu le broken link

2021-01-21 17:20 UTC, lbois commented on views/partials/missions.ejs
> +        href="#cadre-juridique">section cadre juridique</a>)
j'ai corrigé

2021-01-22 09:53 UTC, estellecomment approved these changes
Ca marche pour moi !

2021-01-22 10:14 UTC, estellecomment commented
On peut faire ces magnifiques exemples : 
![Screen Shot 2021-01-22 at 11 12 59](https://user-images.githubusercontent.com/911434/105478077-ff24ef00-5ca2-11eb-851e-3c99ccab5d00.png)
![Screen Shot 2021-01-22 at 11 13 48](https://user-images.githubusercontent.com/911434/105478083-ffbd8580-5ca2-11eb-9981-7900bf63f5b4.png)

2021-01-22 19:30 UTC, jdauphant commented
Le call to action de la landing n'est plus trop visible :
- Je remettrais un bouton "voir les boutons" en bas (en dessous de "Contactez nous" par exemple pour faire remonter les utilisateurs au bon endroit
- Le mettrais les bontons "FAQ" et "Contactez nous" en secondaire
- Je mettrais un séparation avant "Je suis volontaire pour une mission, comment cela se passe-t-il ?" pour indiqué un changement de section, on peut utiliser les sections avec un background et un peu plus d'espace

2021-01-25 16:43 UTC, estellecomment commented on views/partials/contact.ejs
>                                  <span class="rf-text--lg rf-mx-1v">
`rf-text--lg` ne fait rien, on peut l'enlever

2021-01-25 16:44 UTC, estellecomment commented on views/partials/missions.ejs
> +    <h3 id="missions">Les offres de mission disponibles</h3>
ya déja un id "offres-de-mission" ligne 1. Est-ce qu'on peut le réutiliser ?

2021-01-25 16:48 UTC, estellecomment requested changes

2021-01-25 16:48 UTC, estellecomment commented on views/partials/missions.ejs
> +      <h3>Je suis volontaire pour une mission, comment cela se passe-t-il ?</h3>
Je mettrais le titre "Comment ça marche ? " (on n'est plus dans la FAQ, donc la formulation "je suis X, je voudrais Y" est un peu lourde je trouve)

2021-01-25 16:48 UTC, estellecomment commented on views/partials/missions.ejs
> +  <div class="rf-callout">
Le callout est un élément pour attirer l'attention sur une phrase ou une action (voir la doc du DS : https://gouvfr.atlassian.net/wiki/spaces/DB/pages/222331196/Mise+en+avant+-+Call-out)

Donc ici, c'est pas très adapté pour une section entière. Je te propose de s'inspirer de characteristics.ejs, qui utilise la classe `bg-fond-alternatif`

2021-01-27 15:51 UTC, estellecomment approved these changes

2021-01-27 15:51 UTC, estellecomment commented on views/partials/missions.ejs
> +    <div class="rf-col rf-col-9" style="text-align: left; margin-left: 200;">
Eviter de mettre du style comme ca dans le html, il vaut mieux créer une class CSS.

Ici en fait on peut en enlever : 
- `text-align: left;` n'est pas nécessaire si tu enlèves le `rf-centered` 2 lignes plus haut.
- `margin-left: 200` n'est pas appliqué, il apparait barré dans les devtools, donc on peut l'enlever.
![image](https://user-images.githubusercontent.com/911434/106015867-2fafc300-60bf-11eb-956b-e75acc7c8a1a.png)

2021-01-27 15:51 UTC, estellecomment commented on views/partials/missions.ejs
> +    <div class="rf-col rf-col-9" style="text-align: left; margin-left: 200;">
Je propose aussi d'ajouter `rf-mt-4w` pour ajouter un peu d'espace au dessus du titre.

2021-01-27 16:40 UTC, merged